"""
環境測試標準定義 + SOP 步驟整合
架構：三層巢狀 STANDARD_TREE + 向後相容的 STANDARDS_AND_SOPS 平坦結構

資料來源（公開法規）：
- IEC 60068-2-1:2007  (Test A: Cold)
- IEC 60068-2-2:2007  (Test B: Dry Heat)
- IEC 60068-2-14:2023 (Test N: Temperature Change, Na/Nb)
- IEC 60068-2-30:2005 (Test Db: Damp Heat Cyclic)
- EN 50155:2017       (OT1~OT6, ST0/ST1/ST2, Rapid Temp Variation)
- IEC 61850-3 Ed.1:2002 / Ed.2:2013 (Class C1/C2/C3)
- DNVGL-CG-0339:2019  (Location Class A/B/C/D)
- DNV Std.Cert.2.4    (舊版 Class A/B/C/D)
- KEMA KEUR + IEC/CENELEC
- IEC 61162-1:2016 (NMEA 0183) / IEC 61162-3:2010 (NMEA 2000)
"""

from typing import Dict, List, Any, Optional


# ══════════════════════════════════════════════════════════════
# 通用 SOP 步驟工廠（各標準可客制化覆蓋）
# ══════════════════════════════════════════════════════════════


def _steps_single_temp(temp: float, duration_h: int, mode: str = "high") -> list:
    """單一溫度（乾熱/冷測）執行中步驟 — 啟動後才顯示，全部不自動勾選"""
    direction = "高溫" if mode == "high" else "低溫"
    return [
        {
            "step_id": 1,
            "name": f"確認{'升' if mode == 'high' else '降'}溫曲線正常",
            "description": f"監控溫度曲線，確認正在{'升' if mode == 'high' else '降'}溫至 {temp}°C，速率符合標準要求，無異常跳動。",
            "requires_photo": False,
            "requires_parameters": False,
            "optional": False,
        },
        {
            "step_id": 2,
            "name": f"確認達到目標溫度 {temp}°C",
            "description": f"確認溫度已穩定在 {temp}°C ± 容差範圍內，開始計時 {duration_h} 小時停留。",
            "requires_photo": False,
            "requires_parameters": False,
            "optional": False,
        },
        {
            "step_id": 3,
            "name": f"{direction}停留中期確認",
            "description": f"停留時間過半時確認溫度仍穩定，設備與樣品無異常。",
            "requires_photo": False,
            "requires_parameters": False,
            "optional": True,
        },
        {
            "step_id": 4,
            "name": f"{duration_h}h 停留完成，拍照記錄",
            "description": f"確認已完成 {duration_h} 小時{direction}停留，拍照記錄設備狀態與樣品外觀。",
            "requires_photo": True,
            "requires_parameters": False,
            "optional": False,
        },
        {
            "step_id": 5,
            "name": "儲存測試紀錄",
            "description": "點擊儲存按鈕，確認執行紀錄已寫入資料庫，下載 CSV 測試報告。",
            "requires_photo": False,
            "requires_parameters": False,
            "optional": False,
        },
    ]


def _steps_cycle(
    low: float, high: float, cycles: int, humidity: Optional[float] = None
) -> list:
    """循環測試（溫度循環/濕熱循環）執行中步驟 — 啟動後才顯示，全部不自動勾選"""
    humi_note = f"，濕度 {humidity}%RH" if humidity else ""
    return [
        {
            "step_id": 1,
            "name": "確認第一循環升降溫曲線正常",
            "description": f"監控第一個循環的升降溫速率，確認曲線符合標準要求{humi_note}，無異常。",
            "requires_photo": False,
            "requires_parameters": False,
            "optional": False,
        },
        {
            "step_id": 2,
            "name": f"確認高溫 {high}°C 停留正常",
            "description": f"確認溫度穩定在 {high}°C ± 容差，開始計時高溫停留。",
            "requires_photo": False,
            "requires_parameters": False,
            "optional": False,
        },
        {
            "step_id": 3,
            "name": f"確認低溫 {low}°C 停留正常",
            "description": f"確認溫度穩定在 {low}°C ± 容差，開始計時低溫停留。",
            "requires_photo": False,
            "requires_parameters": False,
            "optional": False,
        },
        {
            "step_id": 4,
            "name": "中期循環檢查",
            "description": f"循環過半時確認每個循環的高低溫停留時間正確，有異常立即停止。",
            "requires_photo": False,
            "requires_parameters": False,
            "optional": True,
        },
        {
            "step_id": 5,
            "name": f"全部 {cycles} 循環完成，拍照記錄",
            "description": f"確認 {cycles} 個循環全部完成，設備無異常，拍照記錄最終狀態。",
            "requires_photo": True,
            "requires_parameters": False,
            "optional": False,
        },
        {
            "step_id": 6,
            "name": "儲存測試紀錄",
            "description": "點擊儲存按鈕，確認執行紀錄已寫入資料庫，下載 CSV 測試報告。",
            "requires_photo": False,
            "requires_parameters": False,
            "optional": False,
        },
    ]


# ══════════════════════════════════════════════════════════════
# 三層巢狀標準樹：法規 → 版本 → 測試條件
# ══════════════════════════════════════════════════════════════

STANDARD_TREE: Dict[str, Any] = {
    # ──────────────────────────────────────────────────────────
    # IEC 60068 系列
    # ──────────────────────────────────────────────────────────
    "IEC 60068": {
        "label": "IEC 60068 基礎環境測試",
        "description": "IEC 60068 為所有環境測試之基礎標準，分多個 Part 涵蓋各種應力條件。",
        "versions": {
            "IEC 60068-2-1:2007 (Test A: Cold)": {
                "label": "IEC 60068-2-1:2007 冷測試",
                "description": "低溫儲存（Test Ab）與低溫工作（Test Ad）。",
                "tests": {
                    "Ab_-40_16h": {
                        "sop_id": "iec60068_ab_-40_16h",
                        "name": "低溫儲存 Test Ab：-40°C，16 小時（非通電）",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-1:2007",
                        "description": "Test Ab：非通電狀態，評估產品在低溫儲存環境的耐受性。",
                        "high_temperature": None,
                        "low_temperature": -40.0,
                        "target_temperature": -40.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-1:2007 Test Ab",
                        "steps": _steps_single_temp(-40.0, 16, "low"),
                    },
                    "Ab_-55_16h": {
                        "sop_id": "iec60068_ab_-55_16h",
                        "name": "低溫儲存 Test Ab：-55°C，16 小時（非通電）",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-1:2007",
                        "description": "Test Ab 嚴苛等級：-55°C 非通電低溫儲存。",
                        "high_temperature": None,
                        "low_temperature": -55.0,
                        "target_temperature": -55.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-1:2007 Test Ab",
                        "steps": _steps_single_temp(-55.0, 16, "low"),
                    },
                    "Ad_-25_2h": {
                        "sop_id": "iec60068_ad_-25_2h",
                        "name": "低溫工作 Test Ad：-25°C，2 小時（通電）",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-1:2007",
                        "description": "Test Ad：通電工作狀態，評估產品在低溫下的功能性。",
                        "high_temperature": None,
                        "low_temperature": -25.0,
                        "target_temperature": -25.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 2,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-1:2007 Test Ad",
                        "steps": _steps_single_temp(-25.0, 2, "low"),
                    },
                },
            },
            "IEC 60068-2-2:2007 (Test B: Dry Heat)": {
                "label": "IEC 60068-2-2:2007 乾熱測試",
                "description": "高溫儲存（Test Ba）與高溫工作（Test Bb）。",
                "tests": {
                    "Ba_+85_16h": {
                        "sop_id": "iec60068_ba_+85_16h",
                        "name": "乾熱儲存 Test Ba：+85°C，16 小時（非通電）",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-2:2007",
                        "description": "Test Ba：非通電高溫儲存，評估在高溫下的材料穩定性。",
                        "high_temperature": 85.0,
                        "low_temperature": None,
                        "target_temperature": 85.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-2:2007 Test Ba",
                        "steps": _steps_single_temp(85.0, 16, "high"),
                    },
                    "Ba_+125_2h": {
                        "sop_id": "iec60068_ba_+125_2h",
                        "name": "乾熱儲存 Test Ba：+125°C，2 小時（非通電）",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-2:2007",
                        "description": "Test Ba 嚴苛等級：+125°C 非通電高溫儲存。",
                        "high_temperature": 125.0,
                        "low_temperature": None,
                        "target_temperature": 125.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 2,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-2:2007 Test Ba",
                        "steps": _steps_single_temp(125.0, 2, "high"),
                    },
                    "Bb_+70_16h": {
                        "sop_id": "iec60068_bb_+70_16h",
                        "name": "乾熱工作 Test Bb：+70°C，16 小時（通電）",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-2:2007",
                        "description": "Test Bb：通電工作狀態，評估高溫下的電氣功能性。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-2:2007 Test Bb",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                },
            },
            "IEC 60068-2-14:2023 (Test N: Temp Change)": {
                "label": "IEC 60068-2-14:2023 溫度變化測試",
                "description": "Test Na（空氣對空氣快速熱衝擊）/ Test Nb（單腔線性速率漸進式循環）。最新版 Ed.7 2023年發布。",
                "tests": {
                    "Nb_-40_+85_2Cmin_5cycle": {
                        "sop_id": "iec60068_nb_-40_+85_5cycle",
                        "name": "Test Nb 漸進溫度循環：-40°C ↔ +85°C，2°C/min，5 循環",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-14:2023",
                        "description": "Test Nb：單腔體線性速率升降溫，2°C/min，每端停留 60 分鐘，5 循環。最常用的工業標準溫度循環。",
                        "high_temperature": 85.0,
                        "low_temperature": -40.0,
                        "target_temperature": 85.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 1,
                        "cycles": 5,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-14:2023 Test Nb",
                        "steps": _steps_cycle(-40.0, 85.0, 5),
                    },
                    "Nb_-25_+70_2Cmin_3cycle": {
                        "sop_id": "iec60068_nb_-25_+70_3cycle",
                        "name": "Test Nb 漸進溫度循環：-25°C ↔ +70°C，2°C/min，3 循環",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-14:2023",
                        "description": "Test Nb 溫和等級：單腔體線性速率升降溫，適用於辦公室/工業溫帶環境設備。",
                        "high_temperature": 70.0,
                        "low_temperature": -25.0,
                        "target_temperature": 70.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 1,
                        "cycles": 3,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-14:2023 Test Nb",
                        "steps": _steps_cycle(-25.0, 70.0, 3),
                    },
                    "Na_-55_+125_5cycle": {
                        "sop_id": "iec60068_na_-55_+125_5cycle",
                        "name": "Test Na 熱衝擊：-55°C ↔ +125°C，轉換 < 30 秒，5 循環",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-14:2023",
                        "description": "Test Na：空氣對空氣雙腔體熱衝擊，快速轉換（<30秒），每端停留 30 分鐘，測試焊點/材料熱衝擊耐受性。",
                        "high_temperature": 125.0,
                        "low_temperature": -55.0,
                        "target_temperature": 125.0,
                        "ramp_rate": 30.0,
                        "dwell_time_hours": 0.5,
                        "cycles": 5,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-14:2023 Test Na",
                        "steps": _steps_cycle(-55.0, 125.0, 5),
                    },
                    "Na_-40_+85_5cycle": {
                        "sop_id": "iec60068_na_-40_+85_5cycle",
                        "name": "Test Na 熱衝擊：-40°C ↔ +85°C，轉換 < 30 秒，5 循環",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-14:2023",
                        "description": "Test Na 常用等級：空氣對空氣雙腔體快速熱衝擊，適用於一般工業電子設備。",
                        "high_temperature": 85.0,
                        "low_temperature": -40.0,
                        "target_temperature": 85.0,
                        "ramp_rate": 30.0,
                        "dwell_time_hours": 0.5,
                        "cycles": 5,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-14:2023 Test Na",
                        "steps": _steps_cycle(-40.0, 85.0, 5),
                    },
                },
            },
            "IEC 60068-2-30:2005 (Test Db: Damp Heat Cyclic)": {
                "label": "IEC 60068-2-30:2005 濕熱循環測試",
                "description": "Test Db 交變濕熱循環：25°C↔55°C，95%RH。專門評估結露情況下的腐蝕耐受性。",
                "tests": {
                    "Db_25_55_95RH_6cycle": {
                        "sop_id": "iec60068_db_25_55_6cycle",
                        "name": "濕熱循環 Test Db：25°C ↔ 55°C，95%RH，6 循環（每循環 24h）",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-30:2005",
                        "description": "Test Db：交變濕熱循環，測試結露冷凝對材料、塗層、密封的影響。每循環 24 小時，高溫 12h + 降溫 3~6h + 室溫。",
                        "high_temperature": 55.0,
                        "low_temperature": 25.0,
                        "target_temperature": 55.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 12,
                        "cycles": 6,
                        "humidity_rh_percent": 95.0,
                        "humidity_control": True,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-30:2005 Test Db",
                        "steps": _steps_cycle(25.0, 55.0, 6, 95.0),
                    },
                    "Db_25_40_93RH_2cycle": {
                        "sop_id": "iec60068_db_25_40_2cycle",
                        "name": "濕熱循環 Test Db Variant 1：25°C ↔ 40°C，93%RH，2 循環",
                        "test_type": "chamber",
                        "version": "IEC 60068-2-30:2005",
                        "description": "Test Db 輕度等級（Variant 1）：40°C/93%RH，適用於辦公室/室內設備，2 循環。",
                        "high_temperature": 40.0,
                        "low_temperature": 25.0,
                        "target_temperature": 40.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 12,
                        "cycles": 2,
                        "humidity_rh_percent": 93.0,
                        "humidity_control": True,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60068-2-30:2005 Test Db Variant 1",
                        "steps": _steps_cycle(25.0, 40.0, 2, 93.0),
                    },
                },
            },
        },
    },
    # ──────────────────────────────────────────────────────────
    # EN 50155 歐洲鐵路
    # ──────────────────────────────────────────────────────────
    "EN 50155": {
        "label": "EN 50155 歐洲鐵路電子設備",
        "description": "適用於安裝在鐵路車輛上的電子設備。2017 版引入 OT1~OT6 六個溫度等級，取代 2007 版的 T1/T2/T3/TX。",
        "versions": {
            "EN 50155:2017": {
                "label": "EN 50155:2017（現行版）",
                "description": "現行版本。六個 OT 操作溫度等級，預設 OT3（-25°C ~ +70°C）。新增 Rapid Temperature Variation 測試。",
                "tests": {
                    "OT1_High_Dry_Heat": {
                        "sop_id": "en50155_2017_ot1_high",
                        "name": "OT1 高溫乾熱：+55°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT1 等級（乘客車廂/駕駛室）。高溫上限 +55°C，持續 16 小時，非通電。低溫另測。",
                        "high_temperature": 55.0,
                        "low_temperature": None,
                        "target_temperature": 55.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT1",
                        "steps": _steps_single_temp(55.0, 16, "high"),
                    },
                    "OT1_Low_Cold": {
                        "sop_id": "en50155_2017_ot1_low",
                        "name": "OT1 低溫冷測：-25°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT1 等級低溫。以 IEC 60068-2-1 Test Ab 方法執行，-25°C 持續 16 小時。",
                        "high_temperature": None,
                        "low_temperature": -25.0,
                        "target_temperature": -25.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT1 + IEC 60068-2-1",
                        "steps": _steps_single_temp(-25.0, 16, "low"),
                    },
                    "OT2_High_Dry_Heat": {
                        "sop_id": "en50155_2017_ot2_high",
                        "name": "OT2 高溫乾熱：+55°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT2 等級高溫上限同 OT1（+55°C），但低溫更嚴苛（-40°C）。",
                        "high_temperature": 55.0,
                        "low_temperature": None,
                        "target_temperature": 55.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT2",
                        "steps": _steps_single_temp(55.0, 16, "high"),
                    },
                    "OT2_Low_Cold": {
                        "sop_id": "en50155_2017_ot2_low",
                        "name": "OT2 低溫冷測：-40°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT2 等級低溫。-40°C 持續 16 小時，適用於極端氣候地區的鐵路設備。",
                        "high_temperature": None,
                        "low_temperature": -40.0,
                        "target_temperature": -40.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT2 + IEC 60068-2-1",
                        "steps": _steps_single_temp(-40.0, 16, "low"),
                    },
                    "OT3_High_Dry_Heat": {
                        "sop_id": "en50155_2017_ot3_high",
                        "name": "OT3 高溫乾熱：+70°C，16h（非通電）【預設等級】",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT3 為 EN 50155:2017 預設等級。高溫 +70°C 持續 16 小時，適用於大多數鐵路車載設備。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT3 (Default Level)",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "OT3_Low_Cold": {
                        "sop_id": "en50155_2017_ot3_low",
                        "name": "OT3 低溫冷測：-25°C，16h（非通電）【預設等級】",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT3 預設等級低溫。-25°C 持續 16 小時。",
                        "high_temperature": None,
                        "low_temperature": -25.0,
                        "target_temperature": -25.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT3 (Default Level)",
                        "steps": _steps_single_temp(-25.0, 16, "low"),
                    },
                    "OT3_ST1_High": {
                        "sop_id": "en50155_2017_ot3_st1",
                        "name": "OT3 + ST1 開機延伸：+85°C，10 分鐘（OT3+15°C）",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "ST1 為預設開機延伸溫度等級（OTx+15°C，持續 10 分鐘）。模擬設備在高溫環境下剛開機時的短暫溫度峰值。ST1/ST2 不適用 OT5/OT6。",
                        "high_temperature": 85.0,
                        "low_temperature": None,
                        "target_temperature": 85.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 0.17,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 2 ST1 (OT3+15°C, 10 min)",
                        "steps": [
                            {
                                "step_id": 1,
                                "name": "設備開機與預檢",
                                "description": "確認電源、保險絲、水箱水位正常。",
                                "requires_photo": True,
                                "requires_parameters": False,
                                "optional": False,
                            },
                            {
                                "step_id": 2,
                                "name": "升溫至 OT3+15°C = +85°C",
                                "description": "通電狀態，升溫至 85°C，速率 ≤5°C/min。確認設備在升溫過程中功能正常。",
                                "requires_photo": False,
                                "requires_parameters": False,
                                "optional": False,
                            },
                            {
                                "step_id": 3,
                                "name": "維持 85°C，10 分鐘",
                                "description": "通電狀態維持 +85°C 恰好 10 分鐘（±1 分鐘），監控設備功能是否正常。",
                                "requires_photo": False,
                                "requires_parameters": False,
                                "optional": False,
                            },
                            {
                                "step_id": 4,
                                "name": "測試完成確認",
                                "description": "10 分鐘後確認設備無異常，拍照記錄。",
                                "requires_photo": True,
                                "requires_parameters": False,
                                "optional": False,
                            },
                            {
                                "step_id": 5,
                                "name": "儲存測試紀錄",
                                "description": "點擊儲存按鈕，確認執行紀錄已寫入資料庫。",
                                "requires_photo": False,
                                "requires_parameters": False,
                                "optional": False,
                            },
                        ],
                    },
                    "OT4_High_Dry_Heat": {
                        "sop_id": "en50155_2017_ot4_high",
                        "name": "OT4 高溫乾熱：+70°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT4 等級：高溫同 OT3（+70°C），但低溫更嚴苛（-40°C），適用於寒帶地區車外設備。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT4",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "OT4_Low_Cold": {
                        "sop_id": "en50155_2017_ot4_low",
                        "name": "OT4 低溫冷測：-40°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT4 等級低溫。-40°C 持續 16 小時，適用於北歐/俄羅斯等極寒地區鐵路。",
                        "high_temperature": None,
                        "low_temperature": -40.0,
                        "target_temperature": -40.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT4",
                        "steps": _steps_single_temp(-40.0, 16, "low"),
                    },
                    "OT5_High_Dry_Heat": {
                        "sop_id": "en50155_2017_ot5_high",
                        "name": "OT5 高溫乾熱：+85°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT5 等級：適用於半導體驅動單元(SDU)、引擎控制等高溫設備，高溫 +85°C。ST1/ST2 不適用。",
                        "high_temperature": 85.0,
                        "low_temperature": None,
                        "target_temperature": 85.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT5",
                        "steps": _steps_single_temp(85.0, 16, "high"),
                    },
                    "OT6_High_Dry_Heat": {
                        "sop_id": "en50155_2017_ot6_high",
                        "name": "OT6 高溫乾熱：+85°C，16h（非通電）【最嚴苛】",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT6 最嚴苛等級：高溫 +85°C，低溫 -40°C。適用於車外極端環境設備。ST1/ST2 不適用。",
                        "high_temperature": 85.0,
                        "low_temperature": None,
                        "target_temperature": 85.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT6",
                        "steps": _steps_single_temp(85.0, 16, "high"),
                    },
                    "OT6_Low_Cold": {
                        "sop_id": "en50155_2017_ot6_low",
                        "name": "OT6 低溫冷測：-40°C，16h（非通電）【最嚴苛】",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "OT6 最嚴苛等級低溫。-40°C 持續 16 小時。",
                        "high_temperature": None,
                        "low_temperature": -40.0,
                        "target_temperature": -40.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Table 1 OT6",
                        "steps": _steps_single_temp(-40.0, 16, "low"),
                    },
                    "Rapid_Temp_Variation": {
                        "sop_id": "en50155_2017_rtv",
                        "name": "快速溫度變化測試（隧道模擬）",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "EN 50155:2017 新增。模擬列車進出隧道的快速溫度變化（含結露風險），速率 ≥20°C/min。",
                        "high_temperature": 70.0,
                        "low_temperature": -25.0,
                        "target_temperature": 70.0,
                        "ramp_rate": 20.0,
                        "dwell_time_hours": 0.25,
                        "cycles": 3,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 Clause 4.3.4 Rapid Temperature Variation",
                        "steps": _steps_cycle(-25.0, 70.0, 3),
                    },
                    "Cyclic_Damp_Heat": {
                        "sop_id": "en50155_2017_damp",
                        "name": "濕熱循環測試：25°C ↔ 55°C，93%RH，2 循環（2017 強制）",
                        "test_type": "chamber",
                        "version": "EN 50155:2017",
                        "description": "EN 50155:2017 版起為強制測試項目（2007版為可選）。依 IEC 60068-2-30 Test Db 執行，評估結露對設備的影響。",
                        "high_temperature": 55.0,
                        "low_temperature": 25.0,
                        "target_temperature": 55.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 12,
                        "cycles": 2,
                        "humidity_rh_percent": 93.0,
                        "humidity_control": True,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2017 + IEC 60068-2-30 Test Db",
                        "steps": _steps_cycle(25.0, 55.0, 2, 93.0),
                    },
                },
            },
            "EN 50155:2007": {
                "label": "EN 50155:2007（舊版，T1/T2/T3/TX）",
                "description": "舊版四溫度類別（T1/T2/T3/TX），現有客戶仍使用。2017版已廢止並取代此版本。",
                "tests": {
                    "T1_High_+55": {
                        "sop_id": "en50155_2007_t1_high",
                        "name": "T1 高溫乾熱：+55°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2007",
                        "description": "舊版 T1 等級，高溫上限 +55°C，低溫 -25°C。",
                        "high_temperature": 55.0,
                        "low_temperature": None,
                        "target_temperature": 55.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2007 Clause 12.2.4 T1",
                        "steps": _steps_single_temp(55.0, 16, "high"),
                    },
                    "T2_High_+70": {
                        "sop_id": "en50155_2007_t2_high",
                        "name": "T2 高溫乾熱：+70°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2007",
                        "description": "舊版 T2 等級，高溫上限 +70°C，低溫 -25°C。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2007 Clause 12.2.4 T2",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "T3_High_+85": {
                        "sop_id": "en50155_2007_t3_high",
                        "name": "T3 高溫乾熱：+85°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2007",
                        "description": "舊版 T3 等級，高溫上限 +85°C，低溫 -40°C。",
                        "high_temperature": 85.0,
                        "low_temperature": None,
                        "target_temperature": 85.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2007 Clause 12.2.4 T3",
                        "steps": _steps_single_temp(85.0, 16, "high"),
                    },
                    "TX_Low_-40": {
                        "sop_id": "en50155_2007_tx_low",
                        "name": "TX 低溫儲存：-40°C，16h（非通電）",
                        "test_type": "chamber",
                        "version": "EN 50155:2007",
                        "description": "舊版 TX 等級低溫，-40°C 持續 16 小時，非通電。",
                        "high_temperature": None,
                        "low_temperature": -40.0,
                        "target_temperature": -40.0,
                        "ramp_rate": 5.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "EN 50155:2007 Clause 12.2.4 TX",
                        "steps": _steps_single_temp(-40.0, 16, "low"),
                    },
                },
            },
        },
    },
    # ──────────────────────────────────────────────────────────
    # IEC 61850-3 變電站
    # ──────────────────────────────────────────────────────────
    "IEC 61850-3": {
        "label": "IEC 61850-3 變電站通訊自動化設備",
        "description": "適用於電力廠站與變電站的 IED 通訊設備。環境測試依 IEC 60068 系列執行。",
        "versions": {
            "IEC 61850-3 Ed.2:2013": {
                "label": "IEC 61850-3 Ed.2:2013（現行版）",
                "description": "Ed.2 對應 IEC 60255-27。定義 Class C1（標準室內）、C2（戶外箱體）、C3（嚴苛環境）三個安裝位置等級。",
                "tests": {
                    "C1_Dry_Heat_+55": {
                        "sop_id": "iec61850_ed2_c1_high",
                        "name": "Class C1 乾熱：+55°C，16h（室內標準環境）",
                        "test_type": "chamber",
                        "version": "IEC 61850-3 Ed.2:2013",
                        "description": "C1 等級：標準室內變電站（有空調），工作溫度 -10°C ~ +55°C，依 IEC 60068-2-2 Test Bb 執行。",
                        "high_temperature": 55.0,
                        "low_temperature": None,
                        "target_temperature": 55.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 61850-3:2013 Ed.2 Class C1 + IEC 60068-2-2",
                        "steps": _steps_single_temp(55.0, 16, "high"),
                    },
                    "C1_Cold_-10": {
                        "sop_id": "iec61850_ed2_c1_low",
                        "name": "Class C1 冷測：-10°C，16h（室內標準環境）",
                        "test_type": "chamber",
                        "version": "IEC 61850-3 Ed.2:2013",
                        "description": "C1 等級低溫。-10°C 持續 16 小時，依 IEC 60068-2-1 Test Ab 執行。",
                        "high_temperature": None,
                        "low_temperature": -10.0,
                        "target_temperature": -10.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 61850-3:2013 Ed.2 Class C1 + IEC 60068-2-1",
                        "steps": _steps_single_temp(-10.0, 16, "low"),
                    },
                    "C1_Damp_Heat": {
                        "sop_id": "iec61850_ed2_c1_damp",
                        "name": "Class C1 濕熱循環：25°C ↔ 55°C，95%RH，6 循環",
                        "test_type": "chamber",
                        "version": "IEC 61850-3 Ed.2:2013",
                        "description": "C1 等級濕熱。依 IEC 60068-2-30 Test Db 執行，6 循環，95%RH。",
                        "high_temperature": 55.0,
                        "low_temperature": 25.0,
                        "target_temperature": 55.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 12,
                        "cycles": 6,
                        "humidity_rh_percent": 95.0,
                        "humidity_control": True,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 61850-3:2013 Ed.2 Class C1 + IEC 60068-2-30",
                        "steps": _steps_cycle(25.0, 55.0, 6, 95.0),
                    },
                    "C2_Dry_Heat_+70": {
                        "sop_id": "iec61850_ed2_c2_high",
                        "name": "Class C2 乾熱：+70°C，16h（戶外箱體）",
                        "test_type": "chamber",
                        "version": "IEC 61850-3 Ed.2:2013",
                        "description": "C2 等級：戶外箱體或無空調室內，工作溫度 -25°C ~ +70°C。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 61850-3:2013 Ed.2 Class C2 + IEC 60068-2-2",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "C2_Cold_-25": {
                        "sop_id": "iec61850_ed2_c2_low",
                        "name": "Class C2 冷測：-25°C，16h（戶外箱體）",
                        "test_type": "chamber",
                        "version": "IEC 61850-3 Ed.2:2013",
                        "description": "C2 等級低溫。-25°C 持續 16 小時。",
                        "high_temperature": None,
                        "low_temperature": -25.0,
                        "target_temperature": -25.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 61850-3:2013 Ed.2 Class C2 + IEC 60068-2-1",
                        "steps": _steps_single_temp(-25.0, 16, "low"),
                    },
                    "C3_Dry_Heat_+70": {
                        "sop_id": "iec61850_ed2_c3_high",
                        "name": "Class C3 乾熱：+70°C，16h（嚴苛戶外環境）",
                        "test_type": "chamber",
                        "version": "IEC 61850-3 Ed.2:2013",
                        "description": "C3 等級：嚴苛戶外環境，工作溫度 -40°C ~ +70°C。最嚴苛安裝位置等級。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 61850-3:2013 Ed.2 Class C3 + IEC 60068-2-2",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "C3_Cold_-40": {
                        "sop_id": "iec61850_ed2_c3_low",
                        "name": "Class C3 冷測：-40°C，16h（嚴苛戶外環境）",
                        "test_type": "chamber",
                        "version": "IEC 61850-3 Ed.2:2013",
                        "description": "C3 等級低溫。-40°C 持續 16 小時，最嚴苛低溫要求。",
                        "high_temperature": None,
                        "low_temperature": -40.0,
                        "target_temperature": -40.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 61850-3:2013 Ed.2 Class C3 + IEC 60068-2-1",
                        "steps": _steps_single_temp(-40.0, 16, "low"),
                    },
                },
            },
            "IEC 61850-3 Ed.1:2002": {
                "label": "IEC 61850-3 Ed.1:2002（舊版）",
                "description": "初版，單一環境條件規範，未細分 Class C1/C2/C3。",
                "tests": {
                    "Dry_Heat_+70": {
                        "sop_id": "iec61850_ed1_high",
                        "name": "Ed.1 高溫乾熱：+70°C，16h",
                        "test_type": "chamber",
                        "version": "IEC 61850-3 Ed.1:2002",
                        "description": "Ed.1 標準高溫測試，+70°C 持續 16 小時。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 61850-3:2002 Ed.1",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "Cold_-40": {
                        "sop_id": "iec61850_ed1_low",
                        "name": "Ed.1 低溫冷測：-40°C，16h",
                        "test_type": "chamber",
                        "version": "IEC 61850-3 Ed.1:2002",
                        "description": "Ed.1 標準低溫測試，-40°C 持續 16 小時。",
                        "high_temperature": None,
                        "low_temperature": -40.0,
                        "target_temperature": -40.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 61850-3:2002 Ed.1",
                        "steps": _steps_single_temp(-40.0, 16, "low"),
                    },
                },
            },
        },
    },
    # ──────────────────────────────────────────────────────────
    # DNV 船舶設備
    # ──────────────────────────────────────────────────────────
    "DNV": {
        "label": "DNV 船舶設備環境認證",
        "description": "DNV（Det Norske Veritas）船舶自動化儀器設備認證。依船上安裝位置分 Class A/B/C/D。容差：溫度 ±2°C，濕度 ±10%RH。",
        "versions": {
            "DNVGL-CG-0339:2019": {
                "label": "DNVGL-CG-0339:2019（現行版）",
                "description": "現行版（2019年更新）。Class A/B：乾熱為主，冷測可選。Class C/D：乾熱 + 冷測均強制要求。容差：溫度 ±2°C，濕度 ±10%RH。",
                "tests": {
                    "ClassA_Dry_Heat": {
                        "sop_id": "dnv_cg0339_classa_dry",
                        "name": "Class A 乾熱：+55°C，16h（機艙/控制室）",
                        "test_type": "chamber",
                        "version": "DNVGL-CG-0339:2019",
                        "description": "Class A：機艙、控制室、住艙等有溫度控制的室內環境（環境溫度 0°C ~ +45°C）。乾熱測試 +55°C，冷測可選不強制。",
                        "high_temperature": 55.0,
                        "low_temperature": None,
                        "target_temperature": 55.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNVGL-CG-0339:2019 Table 2 Class A Sec.3[7]",
                        "steps": _steps_single_temp(55.0, 16, "high"),
                    },
                    "ClassA_Damp_Heat": {
                        "sop_id": "dnv_cg0339_classa_damp",
                        "name": "Class A 濕熱（穩態）：+40°C，93%RH，4 天",
                        "test_type": "chamber",
                        "version": "DNVGL-CG-0339:2019",
                        "description": "Class A 濕熱：穩態濕熱（非循環），+40°C，93%RH，持續 96 小時（4 天）。依 IEC 60068-2-78 Test Cab 執行。Class A 選擇穩態或循環其一。",
                        "high_temperature": 40.0,
                        "low_temperature": None,
                        "target_temperature": 40.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 96,
                        "cycles": 1,
                        "humidity_rh_percent": 93.0,
                        "humidity_control": True,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNVGL-CG-0339:2019 Sec.3[8.2] + IEC 60068-2-78 Test Cab",
                        "steps": _steps_single_temp(40.0, 96, "high"),
                    },
                    "ClassB_Dry_Heat": {
                        "sop_id": "dnv_cg0339_classb_dry",
                        "name": "Class B 乾熱：+70°C，16h（箱體內部）",
                        "test_type": "chamber",
                        "version": "DNVGL-CG-0339:2019",
                        "description": "Class B：泵室、貨艙、無加熱艙室等無直接天候暴露的位置。乾熱 +70°C，冷測不強制但建議執行。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNVGL-CG-0339:2019 Table 2 Class B Sec.3[7]",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "ClassB_Damp_Heat_Cyclic": {
                        "sop_id": "dnv_cg0339_classb_damp",
                        "name": "Class B 濕熱循環：25°C ↔ 55°C，95%RH，2 循環",
                        "test_type": "chamber",
                        "version": "DNVGL-CG-0339:2019",
                        "description": "Class B 濕熱循環（結露），依 IEC 60068-2-30 Test Db 執行，2 循環，第一循環通電。",
                        "high_temperature": 55.0,
                        "low_temperature": 25.0,
                        "target_temperature": 55.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 12,
                        "cycles": 2,
                        "humidity_rh_percent": 95.0,
                        "humidity_control": True,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNVGL-CG-0339:2019 Sec.3[8.3] + IEC 60068-2-30 Test Db",
                        "steps": _steps_cycle(25.0, 55.0, 2, 95.0),
                    },
                    "ClassC_Dry_Heat": {
                        "sop_id": "dnv_cg0339_classc_dry",
                        "name": "Class C 乾熱：+70°C，16h（露天甲板）",
                        "test_type": "chamber",
                        "version": "DNVGL-CG-0339:2019",
                        "description": "Class C：露天甲板、無加熱但有遮蔽的位置。乾熱 +70°C 強制，冷測 -25°C 強制。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNVGL-CG-0339:2019 Table 2 Class C Sec.3[7]（強制）",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "ClassC_Cold": {
                        "sop_id": "dnv_cg0339_classc_cold",
                        "name": "Class C 冷測：-25°C，16h（露天甲板）【強制】",
                        "test_type": "chamber",
                        "version": "DNVGL-CG-0339:2019",
                        "description": "Class C 冷測為強制項目（Class A/B 可選，C/D 強制）。-25°C 持續 16 小時。",
                        "high_temperature": None,
                        "low_temperature": -25.0,
                        "target_temperature": -25.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNVGL-CG-0339:2019 Table 2 Class C Sec.3[9]（強制）",
                        "steps": _steps_single_temp(-25.0, 16, "low"),
                    },
                    "ClassD_Dry_Heat": {
                        "sop_id": "dnv_cg0339_classd_dry",
                        "name": "Class D 乾熱：+70°C，16h（水下/極端環境）【強制】",
                        "test_type": "chamber",
                        "version": "DNVGL-CG-0339:2019",
                        "description": "Class D：水下應用、機艙地板下方等極端環境。乾熱 +70°C + 冷測 -40°C 均強制。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNVGL-CG-0339:2019 Table 2 Class D Sec.3[7]（強制）",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "ClassD_Cold": {
                        "sop_id": "dnv_cg0339_classd_cold",
                        "name": "Class D 冷測：-40°C，16h（水下/極端環境）【強制】",
                        "test_type": "chamber",
                        "version": "DNVGL-CG-0339:2019",
                        "description": "Class D 最嚴苛冷測，-40°C 持續 16 小時，強制項目。",
                        "high_temperature": None,
                        "low_temperature": -40.0,
                        "target_temperature": -40.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNVGL-CG-0339:2019 Table 2 Class D Sec.3[9]（強制）",
                        "steps": _steps_single_temp(-40.0, 16, "low"),
                    },
                },
            },
            "DNV Std.Cert.2.4": {
                "label": "DNV Std.Cert.2.4（舊版，仍廣泛使用）",
                "description": "舊版 DNV 2.4 認證，許多現有設備仍持此版認證。與 CG-0339 的主要差別在於測試程序細節。",
                "tests": {
                    "ClassA_Dry_Heat": {
                        "sop_id": "dnv_24_classa_dry",
                        "name": "Class A 乾熱：+55°C（機艙/控制室）",
                        "test_type": "chamber",
                        "version": "DNV Std.Cert.2.4",
                        "description": "舊版 DNV 2.4 Class A 乾熱，+55°C。",
                        "high_temperature": 55.0,
                        "low_temperature": None,
                        "target_temperature": 55.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNV Std.Cert.2.4 Section 3.7 Class A",
                        "steps": _steps_single_temp(55.0, 16, "high"),
                    },
                    "ClassB_Dry_Heat": {
                        "sop_id": "dnv_24_classb_dry",
                        "name": "Class B 乾熱：+70°C（箱體內部）",
                        "test_type": "chamber",
                        "version": "DNV Std.Cert.2.4",
                        "description": "舊版 DNV 2.4 Class B 乾熱，+70°C。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNV Std.Cert.2.4 Section 3.7 Class B",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "ClassC_Cold": {
                        "sop_id": "dnv_24_classc_cold",
                        "name": "Class C 冷測：-25°C（露天甲板）【強制】",
                        "test_type": "chamber",
                        "version": "DNV Std.Cert.2.4",
                        "description": "舊版 DNV 2.4 Class C 冷測，-25°C 強制。",
                        "high_temperature": None,
                        "low_temperature": -25.0,
                        "target_temperature": -25.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNV Std.Cert.2.4 Section 3.9 Class C",
                        "steps": _steps_single_temp(-25.0, 16, "low"),
                    },
                    "ClassD_Cold": {
                        "sop_id": "dnv_24_classd_cold",
                        "name": "Class D 冷測：-40°C（水下/極端環境）【強制】",
                        "test_type": "chamber",
                        "version": "DNV Std.Cert.2.4",
                        "description": "舊版 DNV 2.4 Class D 冷測，-40°C 強制。",
                        "high_temperature": None,
                        "low_temperature": -40.0,
                        "target_temperature": -40.0,
                        "ramp_rate": 3.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 10.0,
                        "reference": "DNV Std.Cert.2.4 Section 3.9 Class D",
                        "steps": _steps_single_temp(-40.0, 16, "low"),
                    },
                },
            },
        },
    },
    # ──────────────────────────────────────────────────────────
    # KEMA 電力設備認證
    # ──────────────────────────────────────────────────────────
    "KEMA": {
        "label": "KEMA / CENELEC 電力設備認證",
        "description": "KEMA KEUR 認證，基於 IEC/CENELEC 標準，適用於電力基礎設施設備。KEMA Labs 為 ISO/IEC 17025 認可實驗室。",
        "versions": {
            "KEMA KEUR (IEC/CENELEC)": {
                "label": "KEMA KEUR（現行，基於 IEC/CENELEC）",
                "description": "KEMA 認證測試依 IEC 60068 系列執行，無獨立溫箱測試標準，由 KEMA Labs 依客戶規格客制化測試程序。",
                "tests": {
                    "Dry_Heat_+70": {
                        "sop_id": "kema_dry_heat_70",
                        "name": "乾熱測試：+70°C，16h（IEC 60068-2-2 Test Bb）",
                        "test_type": "chamber",
                        "version": "KEMA KEUR",
                        "description": "KEMA 電力設備高溫工作測試，+70°C 持續 16 小時，通電狀態，依 IEC 60068-2-2 Test Bb 執行。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "KEMA KEUR + IEC 60068-2-2 Test Bb",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "Cold_-25": {
                        "sop_id": "kema_cold_-25",
                        "name": "冷測試：-25°C，16h（IEC 60068-2-1 Test Ab）",
                        "test_type": "chamber",
                        "version": "KEMA KEUR",
                        "description": "KEMA 電力設備低溫儲存測試，-25°C 持續 16 小時，非通電，依 IEC 60068-2-1 Test Ab 執行。",
                        "high_temperature": None,
                        "low_temperature": -25.0,
                        "target_temperature": -25.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "KEMA KEUR + IEC 60068-2-1 Test Ab",
                        "steps": _steps_single_temp(-25.0, 16, "low"),
                    },
                    "Damp_Heat_+40_93RH": {
                        "sop_id": "kema_damp_40_93rh",
                        "name": "濕熱穩態：+40°C，93%RH，4 天（IEC 60068-2-78）",
                        "test_type": "chamber",
                        "version": "KEMA KEUR",
                        "description": "KEMA 電力設備濕熱穩態測試，+40°C，93%RH，持續 96 小時（4 天）。依 IEC 60068-2-78 Test Cab 執行。",
                        "high_temperature": 40.0,
                        "low_temperature": None,
                        "target_temperature": 40.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 96,
                        "cycles": 1,
                        "humidity_rh_percent": 93.0,
                        "humidity_control": True,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "KEMA KEUR + IEC 60068-2-78 Test Cab",
                        "steps": _steps_single_temp(40.0, 96, "high"),
                    },
                    "Temp_Cycle_-25_+70": {
                        "sop_id": "kema_cycle_-25_+70",
                        "name": "溫度循環：-25°C ↔ +70°C，3 循環（IEC 60068-2-14 Test Nb）",
                        "test_type": "chamber",
                        "version": "KEMA KEUR",
                        "description": "KEMA 電力設備溫度循環，-25°C ↔ +70°C，2°C/min，3 循環，依 IEC 60068-2-14 Test Nb 執行。",
                        "high_temperature": 70.0,
                        "low_temperature": -25.0,
                        "target_temperature": 70.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 1,
                        "cycles": 3,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "KEMA KEUR + IEC 60068-2-14 Test Nb",
                        "steps": _steps_cycle(-25.0, 70.0, 3),
                    },
                },
            },
        },
    },
    # ──────────────────────────────────────────────────────────
    # NMEA 航海電子
    # ──────────────────────────────────────────────────────────
    "NMEA": {
        "label": "NMEA / IEC 61162 航海電子設備",
        "description": "NMEA 0183/2000 對應 IEC 61162-1/3。航海電子設備須通過 IEC 60945 通用要求，含高溫/低溫/濕熱測試。",
        "versions": {
            "IEC 61162-1:2016 / IEC 60945 (NMEA 0183)": {
                "label": "IEC 61162-1:2016 / IEC 60945（NMEA 0183，現行版）",
                "description": "NMEA 0183 單向串列通訊設備。環境測試依 IEC 60945:2002（Maritime Navigation Equipment 通用要求）執行。溫度範圍 -15°C ~ +55°C（暴露裝置至 +70°C）。",
                "tests": {
                    "Dry_Heat_+55_Protected": {
                        "sop_id": "nmea_0183_dry_+55",
                        "name": "高溫工作：+55°C，16h（受保護裝置）",
                        "test_type": "chamber",
                        "version": "IEC 61162-1:2016 / IEC 60945",
                        "description": "受保護安裝（橋樓室內），工作溫度上限 +55°C，依 IEC 60068-2-2 Test Bb 執行，通電狀態。",
                        "high_temperature": 55.0,
                        "low_temperature": None,
                        "target_temperature": 55.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60945:2002 + IEC 61162-1:2016 Section 5",
                        "steps": _steps_single_temp(55.0, 16, "high"),
                    },
                    "Dry_Heat_+70_Exposed": {
                        "sop_id": "nmea_0183_dry_+70",
                        "name": "高溫工作：+70°C，16h（暴露裝置）",
                        "test_type": "chamber",
                        "version": "IEC 61162-1:2016 / IEC 60945",
                        "description": "暴露安裝（甲板/橋樓外部），工作溫度上限 +70°C，依 IEC 60068-2-2 Test Bb 執行，通電狀態。",
                        "high_temperature": 70.0,
                        "low_temperature": None,
                        "target_temperature": 70.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60945:2002 Exposed Equipment + IEC 61162-1:2016",
                        "steps": _steps_single_temp(70.0, 16, "high"),
                    },
                    "Cold_-15": {
                        "sop_id": "nmea_0183_cold_-15",
                        "name": "低溫儲存：-15°C，16h（IEC 60068-2-1 Test Ab）",
                        "test_type": "chamber",
                        "version": "IEC 61162-1:2016 / IEC 60945",
                        "description": "航海電子設備低溫儲存，-15°C 持續 16 小時，非通電。",
                        "high_temperature": None,
                        "low_temperature": -15.0,
                        "target_temperature": -15.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60945:2002 + IEC 61162-1:2016 + IEC 60068-2-1",
                        "steps": _steps_single_temp(-15.0, 16, "low"),
                    },
                    "Damp_Heat": {
                        "sop_id": "nmea_0183_damp",
                        "name": "濕熱穩態：+40°C，93%RH，4 天（IEC 60068-2-78）",
                        "test_type": "chamber",
                        "version": "IEC 61162-1:2016 / IEC 60945",
                        "description": "航海電子設備濕熱測試，海洋高濕環境，+40°C，93%RH，持續 96 小時。",
                        "high_temperature": 40.0,
                        "low_temperature": None,
                        "target_temperature": 40.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 96,
                        "cycles": 1,
                        "humidity_rh_percent": 93.0,
                        "humidity_control": True,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60945:2002 Clause 8.8 + IEC 60068-2-78",
                        "steps": _steps_single_temp(40.0, 96, "high"),
                    },
                    "Temp_Cycle": {
                        "sop_id": "nmea_0183_cycle",
                        "name": "溫度循環：-15°C ↔ +55°C，2°C/min，3 循環",
                        "test_type": "chamber",
                        "version": "IEC 61162-1:2016 / IEC 60945",
                        "description": "航海電子設備溫度循環，模擬航行中溫度變化，3 循環，每端停留 60 分鐘。",
                        "high_temperature": 55.0,
                        "low_temperature": -15.0,
                        "target_temperature": 55.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 1,
                        "cycles": 3,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60945:2002 + IEC 60068-2-14 Test Nb",
                        "steps": _steps_cycle(-15.0, 55.0, 3),
                    },
                },
            },
            "IEC 61162-3:2010 / IEC 60945 (NMEA 2000)": {
                "label": "IEC 61162-3:2010 / IEC 60945（NMEA 2000，現行版）",
                "description": "NMEA 2000 雙向網路通訊，適用於現代整合船用系統（CAN bus）。環境測試同 IEC 60945 要求。",
                "tests": {
                    "Dry_Heat_+55": {
                        "sop_id": "nmea_2000_dry_+55",
                        "name": "高溫工作：+55°C，16h（受保護裝置）",
                        "test_type": "chamber",
                        "version": "IEC 61162-3:2010 / IEC 60945",
                        "description": "NMEA 2000 網路設備高溫工作測試，+55°C 持續 16 小時，通電狀態。",
                        "high_temperature": 55.0,
                        "low_temperature": None,
                        "target_temperature": 55.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": True,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60945:2002 + IEC 61162-3:2010",
                        "steps": _steps_single_temp(55.0, 16, "high"),
                    },
                    "Cold_-15": {
                        "sop_id": "nmea_2000_cold_-15",
                        "name": "低溫儲存：-15°C，16h",
                        "test_type": "chamber",
                        "version": "IEC 61162-3:2010 / IEC 60945",
                        "description": "NMEA 2000 網路設備低溫儲存測試，-15°C 持續 16 小時，非通電。",
                        "high_temperature": None,
                        "low_temperature": -15.0,
                        "target_temperature": -15.0,
                        "ramp_rate": 2.0,
                        "dwell_time_hours": 16,
                        "cycles": 1,
                        "humidity_rh_percent": None,
                        "humidity_control": False,
                        "power_on": False,
                        "temp_tolerance": 2.0,
                        "humi_tolerance": 5.0,
                        "reference": "IEC 60945:2002 + IEC 61162-3:2010",
                        "steps": _steps_single_temp(-15.0, 16, "low"),
                    },
                },
            },
        },
    },
}


# ══════════════════════════════════════════════════════════════
# 向後相容：從 STANDARD_TREE 自動展開 STANDARDS_AND_SOPS
# 供 sop.py / main.py / reports.py 使用
# ══════════════════════════════════════════════════════════════


def _build_flat_standards() -> Dict[str, Any]:
    """將 STANDARD_TREE 展開為向後相容的平坦結構"""
    flat: Dict[str, Any] = {}
    for std_key, std_data in STANDARD_TREE.items():
        for ver_key, ver_data in std_data["versions"].items():
            for test_key, test_data in ver_data["tests"].items():
                sop_id = test_data["sop_id"]
                flat[sop_id] = {
                    **test_data,
                    # 補齊舊欄位名稱
                    "standard_id": sop_id,
                    "standard_family": std_key,
                    "standard_version": ver_key,
                    "number_of_cycles": test_data.get("cycles", 1),
                    "ramp_rate_max": test_data.get("ramp_rate", 3.0),
                    "dwell_time_hours": test_data.get("dwell_time_hours", 1),
                }
    return flat


STANDARDS_AND_SOPS: Dict[str, Any] = _build_flat_standards()


# ══════════════════════════════════════════════════════════════
# 工具函數
# ══════════════════════════════════════════════════════════════


def get_standard(sop_id: str) -> Dict[str, Any]:
    """依 sop_id 取得測試條件（向後相容）"""
    return STANDARDS_AND_SOPS.get(sop_id, {})


def get_ramp_rate(sop_id: str) -> float:
    """取得升降溫速率（°C/min）"""
    std = get_standard(sop_id)
    return std.get("ramp_rate", 2.0)


def get_all_standards() -> list:
    return list(STANDARDS_AND_SOPS.keys())


def get_sop_by_standard(sop_id: str) -> Optional[Dict[str, Any]]:
    """依 sop_id 取得完整 SOP 定義（向後相容）"""
    std = get_standard(sop_id)
    if not std:
        return None
    return {
        "sop_id": std["sop_id"],
        "name": std["name"],
        "test_type": std["test_type"],
        "version": std["version"],
        "description": std.get("description", ""),
        "steps": std.get("steps", []),
    }


def get_standard_tree() -> Dict[str, Any]:
    """取得完整三層標準樹（供前端 UI 使用）"""
    return STANDARD_TREE
